#pragma once

#define MI_ICON_MIN "A"

#define MI_ICON_FOLDER "A"
#define MI_ICON_SOLID_FOLDER "B"
#define MI_ICON_ADD_FOLDER "C"
#define MI_ICON_RESERVED "D"
#define MI_ICON_SOLID_CLOUD "E"
#define MI_ICON_CLOUD "F"
#define MI_ICON_TO_CLOUD "G"
#define MI_ICON_FROM_CLOUD "H"
#define MI_ICON_SNAPSHOT "I"
#define MI_ICON_CAMERA "J"
#define MI_ICON_ADD_CAMERA "K"
#define MI_ICON_REFER_TO_NODES "L"
#define MI_ICON_TRANSLATE "M"
#define MI_ICON_ROTATE "N"
#define MI_ICON_SCALE "O"
#define MI_ICON_CUBE "P"
#define MI_ICON_ADD_CUBE "Q"
#define MI_ICON_LAYERS "R"
#define MI_ICON_ADD_LAYER "S"
#define MI_ICON_REMOVE_LAYER "T"
#define MI_ICON_TRANSPORT_PLAY "U"
#define MI_ICON_TRANSPORT_STOP "V"
#define MI_ICON_TRANSPORT_PAUSE "W"
#define MI_ICON_TRANSPORT_STEP "X"
#define MI_ICON_TRANSPORT_STEP_BACK "Y"
#define MI_ICON_TRANSPORT_REWIND "Z"
#define MI_ICON_TRANSPORT_FAST_FORWARD "a"

#define MI_ICON_MAX "a"
